#!/bin/bash

echo ""
echo "Welcome to the UnoDevContainerApp dev container for WASM."
echo ""
echo "On the first run:"
echo "- Ignore the error that says \"Cannot activate the 'Uno Platform' extension (...)\""
echo "- Follow the instructions in \"solution-config.props.sample\" and uncomment line 16"
echo "- Build the solution"
echo "- Run \"Restart OmniSharp\" from the command palette"
echo ""
echo "GitHub Codespaces considerations:"
echo "- Set the port 5000 visibility to \"Public\" - be advised that this enables outside anonymous access"
echo "- The browser will not recognize the application as a PWA"
echo ""
echo "Useful commands:"
echo "- build: dotnet build UnoDevContainerApp.DevContainer.slnf"
echo "- run:   dotnet run --project UnoDevContainerApp.Wasm"
echo ""
